// <auto-generated />
using System;
using JobBot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobBot.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250224220525_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("JobBot.Database.JobPosting", b =>
                {
                    b.Property<long>("JobPostingID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Applied")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatePulled")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Dental")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EasyApply")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Has401k")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRepost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastDatePulled")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Medical")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoApplyReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Vision")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobPostingID");

                    b.ToTable("JobPostings", (string)null);
                });

            modelBuilder.Entity("JobBot.Database.JobPostingDetail", b =>
                {
                    b.Property<long>("JobPostingID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("JobPostingID");

                    b.ToTable("JobPostingDetails", (string)null);
                });

            modelBuilder.Entity("JobBot.Database.JobPostingQuestion", b =>
                {
                    b.Property<long>("JobPostingID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionKind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionPage")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobPostingID", "Label", "QuestionKind");

                    b.HasIndex("Label", "QuestionKind");

                    b.ToTable("JobPostingQuestions", (string)null);
                });

            modelBuilder.Entity("JobBot.Database.Option", b =>
                {
                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionKind")
                        .HasColumnType("INTEGER");

                    b.HasKey("Value", "Label", "QuestionKind");

                    b.HasIndex("Label", "QuestionKind");

                    b.ToTable("Options", (string)null);
                });

            modelBuilder.Entity("JobBot.Database.Question", b =>
                {
                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionKind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InputType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Label", "QuestionKind");

                    b.HasIndex("Value", "Label", "QuestionKind")
                        .IsUnique();

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("JobBot.Database.JobPostingDetail", b =>
                {
                    b.HasOne("JobBot.Database.JobPosting", "JobPosting")
                        .WithOne("JobPostingDetail")
                        .HasForeignKey("JobBot.Database.JobPostingDetail", "JobPostingID");

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("JobBot.Database.JobPostingQuestion", b =>
                {
                    b.HasOne("JobBot.Database.JobPosting", "JobPosting")
                        .WithMany("JobPostingQuestions")
                        .HasForeignKey("JobPostingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobBot.Database.Question", "Question")
                        .WithMany("JobPostingQuestions")
                        .HasForeignKey("Label", "QuestionKind")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPosting");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("JobBot.Database.Option", b =>
                {
                    b.HasOne("JobBot.Database.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("Label", "QuestionKind")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("JobBot.Database.Question", b =>
                {
                    b.HasOne("JobBot.Database.Option", "Option")
                        .WithOne("SelectedQuestion")
                        .HasForeignKey("JobBot.Database.Question", "Value", "Label", "QuestionKind");

                    b.Navigation("Option");
                });

            modelBuilder.Entity("JobBot.Database.JobPosting", b =>
                {
                    b.Navigation("JobPostingDetail");

                    b.Navigation("JobPostingQuestions");
                });

            modelBuilder.Entity("JobBot.Database.Option", b =>
                {
                    b.Navigation("SelectedQuestion");
                });

            modelBuilder.Entity("JobBot.Database.Question", b =>
                {
                    b.Navigation("JobPostingQuestions");

                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
