// <auto-generated />
using System;
using JobBot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobBot.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250210024003_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("JobBot.Database.AutoLine", b =>
                {
                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("AutoLineValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionPage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Label");

                    b.ToTable("AutoLines", (string)null);
                });

            modelBuilder.Entity("JobBot.Database.ComboBox", b =>
                {
                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionPage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedOptionValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Label");

                    b.HasIndex("SelectedOptionValue", "Label")
                        .IsUnique();

                    b.ToTable("ComboBoxes", (string)null);
                });

            modelBuilder.Entity("JobBot.Database.ComboBoxOption", b =>
                {
                    b.Property<string>("OptionValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.HasKey("OptionValue", "Label");

                    b.HasIndex("Label");

                    b.ToTable("ComboBoxOptions", (string)null);
                });

            modelBuilder.Entity("JobBot.Database.JobPosting", b =>
                {
                    b.Property<long>("JobPostingID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Applied")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatePulled")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Dental")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EasyApply")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Has401k")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRepost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastDatePulled")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Medical")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoApplyReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Vision")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobPostingID");

                    b.ToTable("JobPostings", (string)null);
                });

            modelBuilder.Entity("JobBot.Database.JobPostingAutoLine", b =>
                {
                    b.Property<long>("JobPostingID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.HasKey("JobPostingID", "Label");

                    b.HasIndex("Label");

                    b.ToTable("JobPostingAutoLines", (string)null);
                });

            modelBuilder.Entity("JobBot.Database.JobPostingComboBox", b =>
                {
                    b.Property<long>("JobPostingID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.HasKey("JobPostingID", "Label");

                    b.HasIndex("Label");

                    b.ToTable("JobPostingComboBoxes", (string)null);
                });

            modelBuilder.Entity("JobBot.Database.JobPostingRadio", b =>
                {
                    b.Property<long>("JobPostingID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.HasKey("JobPostingID", "Label");

                    b.HasIndex("Label");

                    b.ToTable("JobPostingRadios", (string)null);
                });

            modelBuilder.Entity("JobBot.Database.JobPostingSingleLine", b =>
                {
                    b.Property<long>("JobPostingID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.HasKey("JobPostingID", "Label");

                    b.HasIndex("Label");

                    b.ToTable("JobPostingSingleLines", (string)null);
                });

            modelBuilder.Entity("JobBot.Database.Radio", b =>
                {
                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionPage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedOptionValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Label");

                    b.HasIndex("SelectedOptionValue", "Label")
                        .IsUnique();

                    b.ToTable("Radios", (string)null);
                });

            modelBuilder.Entity("JobBot.Database.RadioOption", b =>
                {
                    b.Property<string>("OptionValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.HasKey("OptionValue", "Label");

                    b.HasIndex("Label");

                    b.ToTable("RadioOptions", (string)null);
                });

            modelBuilder.Entity("JobBot.Database.SingleLine", b =>
                {
                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionPage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SingleLineValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Label");

                    b.ToTable("SingleLines", (string)null);
                });

            modelBuilder.Entity("JobBot.Database.ComboBox", b =>
                {
                    b.HasOne("JobBot.Database.ComboBoxOption", "SelectedComboBoxOption")
                        .WithOne("SelectedComboBox")
                        .HasForeignKey("JobBot.Database.ComboBox", "SelectedOptionValue", "Label");

                    b.Navigation("SelectedComboBoxOption");
                });

            modelBuilder.Entity("JobBot.Database.ComboBoxOption", b =>
                {
                    b.HasOne("JobBot.Database.ComboBox", "ComboBox")
                        .WithMany("ComboBoxOptions")
                        .HasForeignKey("Label")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComboBox");
                });

            modelBuilder.Entity("JobBot.Database.JobPostingAutoLine", b =>
                {
                    b.HasOne("JobBot.Database.JobPosting", "JobPosting")
                        .WithMany("JobPostingAutoLines")
                        .HasForeignKey("JobPostingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobBot.Database.AutoLine", "AutoLine")
                        .WithMany("JobPostingAutoLines")
                        .HasForeignKey("Label")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutoLine");

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("JobBot.Database.JobPostingComboBox", b =>
                {
                    b.HasOne("JobBot.Database.JobPosting", "JobPosting")
                        .WithMany("JobPostingComboBoxes")
                        .HasForeignKey("JobPostingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobBot.Database.ComboBox", "ComboBox")
                        .WithMany("JobPostingComboBoxes")
                        .HasForeignKey("Label")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComboBox");

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("JobBot.Database.JobPostingRadio", b =>
                {
                    b.HasOne("JobBot.Database.JobPosting", "JobPosting")
                        .WithMany("JobPostingRadios")
                        .HasForeignKey("JobPostingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobBot.Database.Radio", "Radio")
                        .WithMany("JobPostingRadios")
                        .HasForeignKey("Label")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPosting");

                    b.Navigation("Radio");
                });

            modelBuilder.Entity("JobBot.Database.JobPostingSingleLine", b =>
                {
                    b.HasOne("JobBot.Database.JobPosting", "JobPosting")
                        .WithMany("JobPostingSingleLines")
                        .HasForeignKey("JobPostingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobBot.Database.SingleLine", "SingleLine")
                        .WithMany("JobPostingSingleLines")
                        .HasForeignKey("Label")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPosting");

                    b.Navigation("SingleLine");
                });

            modelBuilder.Entity("JobBot.Database.Radio", b =>
                {
                    b.HasOne("JobBot.Database.RadioOption", "SelectedRadioOption")
                        .WithOne("SelectedRadio")
                        .HasForeignKey("JobBot.Database.Radio", "SelectedOptionValue", "Label");

                    b.Navigation("SelectedRadioOption");
                });

            modelBuilder.Entity("JobBot.Database.RadioOption", b =>
                {
                    b.HasOne("JobBot.Database.Radio", "Radio")
                        .WithMany("RadioOptions")
                        .HasForeignKey("Label")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Radio");
                });

            modelBuilder.Entity("JobBot.Database.AutoLine", b =>
                {
                    b.Navigation("JobPostingAutoLines");
                });

            modelBuilder.Entity("JobBot.Database.ComboBox", b =>
                {
                    b.Navigation("ComboBoxOptions");

                    b.Navigation("JobPostingComboBoxes");
                });

            modelBuilder.Entity("JobBot.Database.ComboBoxOption", b =>
                {
                    b.Navigation("SelectedComboBox");
                });

            modelBuilder.Entity("JobBot.Database.JobPosting", b =>
                {
                    b.Navigation("JobPostingAutoLines");

                    b.Navigation("JobPostingComboBoxes");

                    b.Navigation("JobPostingRadios");

                    b.Navigation("JobPostingSingleLines");
                });

            modelBuilder.Entity("JobBot.Database.Radio", b =>
                {
                    b.Navigation("JobPostingRadios");

                    b.Navigation("RadioOptions");
                });

            modelBuilder.Entity("JobBot.Database.RadioOption", b =>
                {
                    b.Navigation("SelectedRadio");
                });

            modelBuilder.Entity("JobBot.Database.SingleLine", b =>
                {
                    b.Navigation("JobPostingSingleLines");
                });
#pragma warning restore 612, 618
        }
    }
}
