// <auto-generated />
using System;
using JobBot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobBot.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("JobBot.Database.JobPosting", b =>
                {
                    b.Property<long>("JobPostingID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatePulled")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Dental")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EasyApply")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Has401k")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRepost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Medical")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Vision")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobPostingID");

                    b.ToTable("JobPostings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
