// <auto-generated />
using System;
using JobBot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobBot.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("JobBot.Database.ComboBox", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedOptionValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("SelectedOptionValue", "Key")
                        .IsUnique();

                    b.ToTable("ComboBoxes", (string)null);
                });

            modelBuilder.Entity("JobBot.Database.ComboBoxOption", b =>
                {
                    b.Property<string>("OptionValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.HasKey("OptionValue", "Key");

                    b.HasIndex("Key");

                    b.ToTable("ComboBoxOptions", (string)null);
                });

            modelBuilder.Entity("JobBot.Database.JobPosting", b =>
                {
                    b.Property<long>("JobPostingID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Applied")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatePulled")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Dental")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EasyApply")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Has401k")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRepost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastDatePulled")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Medical")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoApplyReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Vision")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobPostingID");

                    b.ToTable("JobPostings", (string)null);
                });

            modelBuilder.Entity("JobBot.Database.JobPostingComboBox", b =>
                {
                    b.Property<long>("JobPostingID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.HasKey("JobPostingID", "Key");

                    b.HasIndex("Key");

                    b.ToTable("JobPostingComboBoxes", (string)null);
                });

            modelBuilder.Entity("JobBot.Database.JobPostingSingleLine", b =>
                {
                    b.Property<long>("JobPostingID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.HasKey("JobPostingID", "Key");

                    b.HasIndex("Key");

                    b.ToTable("JobPostingSingleLines", (string)null);
                });

            modelBuilder.Entity("JobBot.Database.SingleLine", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SingleLineValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("SingleLines", (string)null);
                });

            modelBuilder.Entity("JobBot.Database.ComboBox", b =>
                {
                    b.HasOne("JobBot.Database.ComboBoxOption", "SelectedComboBoxOption")
                        .WithOne("SelectedComboBox")
                        .HasForeignKey("JobBot.Database.ComboBox", "SelectedOptionValue", "Key");

                    b.Navigation("SelectedComboBoxOption");
                });

            modelBuilder.Entity("JobBot.Database.ComboBoxOption", b =>
                {
                    b.HasOne("JobBot.Database.ComboBox", "ComboBox")
                        .WithMany("ComboBoxOptions")
                        .HasForeignKey("Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComboBox");
                });

            modelBuilder.Entity("JobBot.Database.JobPostingComboBox", b =>
                {
                    b.HasOne("JobBot.Database.JobPosting", "JobPosting")
                        .WithMany("JobPostingComboBoxes")
                        .HasForeignKey("JobPostingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobBot.Database.ComboBox", "ComboBox")
                        .WithMany("JobPostingComboBoxes")
                        .HasForeignKey("Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComboBox");

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("JobBot.Database.JobPostingSingleLine", b =>
                {
                    b.HasOne("JobBot.Database.JobPosting", "JobPosting")
                        .WithMany("JobPostingSingleLines")
                        .HasForeignKey("JobPostingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobBot.Database.SingleLine", "SingleLine")
                        .WithMany("JobPostingSingleLines")
                        .HasForeignKey("Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPosting");

                    b.Navigation("SingleLine");
                });

            modelBuilder.Entity("JobBot.Database.ComboBox", b =>
                {
                    b.Navigation("ComboBoxOptions");

                    b.Navigation("JobPostingComboBoxes");
                });

            modelBuilder.Entity("JobBot.Database.ComboBoxOption", b =>
                {
                    b.Navigation("SelectedComboBox");
                });

            modelBuilder.Entity("JobBot.Database.JobPosting", b =>
                {
                    b.Navigation("JobPostingComboBoxes");

                    b.Navigation("JobPostingSingleLines");
                });

            modelBuilder.Entity("JobBot.Database.SingleLine", b =>
                {
                    b.Navigation("JobPostingSingleLines");
                });
#pragma warning restore 612, 618
        }
    }
}
